var admin=function(){var r={vars:{"dependAttempts":0,"tags":['IS_FRESH','IS_NEEDREVIEW','IS_HASERRORS','IS_CONFIGABLE','IS_COLORFUL','IS_SIZEABLE','IS_OPENBOX','IS_PREORDER','IS_DISCONTINUED','IS_SPECIALORDER','IS_BESTSELLER','IS_SALE','IS_SHIPFREE','IS_NEWARRIVAL','IS_CLEARANCE','IS_REFURB','IS_USER1','IS_USER2','IS_USER3','IS_USER4','IS_USER5','IS_USER6','IS_USER7','IS_USER8','IS_USER9'],"dependencies":['store_prodlist','store_navcats','store_product','store_search']},calls:{navcats:{appCategoryDetailNoLocal:{init:function(path,tagObj,Q){tagObj=typeof tagObj!=='object'?{}:tagObj;tagObj.datapointer='appCategoryDetail|'+path;this.dispatch(path,tagObj,Q);return 1;},dispatch:function(path,tagObj,Q){myControl.model.addDispatchToQ({"_cmd":"appCategoryDetail","safe":path,"detail":"fast","_tag":tagObj},Q);}}},appResource:{init:function(filename){this.dispatch(filename);},dispatch:function(filename){myControl.model.addDispatchToQ({"_cmd":"appResource","filename":filename,"_tag":{"datapointer":"adminImageFolderList"}});}},mediaLib:{adminImageFolderList:{init:function(){this.dispatch();},dispatch:function(){myControl.model.addDispatchToQ({"_cmd":"adminImageFolderList","_tag":{"datapointer":"adminImageFolderList"}});}}},product:{appProductGetNoLocal:{init:function(pid,tagObj,Q){this.dispatch(pid,tagObj,Q)
return 1;},dispatch:function(pid,tagObj,Q){var obj={};tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj["datapointer"]="appProductGet|"+pid;obj["_cmd"]="appProductGet";obj["pid"]=pid;obj["_tag"]=tagObj;myControl.model.addDispatchToQ(obj,Q);}},adminProductUpdate:{init:function(pid,attrObj,tagObj){this.dispatch(pid,attrObj,tagObj)
return 1;},dispatch:function(pid,attrObj,tagObj){var obj={};tagObj=$.isEmptyObject(tagObj)?{}:tagObj;obj["_cmd"]="adminProductUpdate";obj["product"]=pid;obj['%attribs']=attrObj;obj["_tag"]=tagObj;myControl.model.addDispatchToQ(obj,'immutable');}}},finder:{adminNavcatProductInsert:{init:function(pid,position,path,tagObj){this.dispatch(pid,position,path,tagObj);return 1;},dispatch:function(pid,position,path,tagObj){var obj={};obj['_tag']=typeof tagObj=='object'?tagObj:{};obj['_cmd']="adminNavcatProductInsert";obj.product=pid;obj.path=path;obj.position=position;obj['_tag'].datapointer="adminNavcatProductInsert|"+path+"|"+pid;myControl.model.addDispatchToQ(obj,'immutable');}},adminNavcatProductDelete:{init:function(pid,path,tagObj){this.dispatch(pid,path,tagObj);},dispatch:function(pid,path,tagObj){var obj={};obj['_tag']=typeof tagObj=='object'?tagObj:{};obj['_cmd']="adminNavcatProductDelete";obj.product=pid;obj.path=path;obj['_tag'].datapointer="adminNavcatProductDelete|"+path+"|"+pid;myControl.model.addDispatchToQ(obj,'immutable');}}}},callbacks:{init:{onSuccess:function(){var r=true;var $templateDiv=$('<div \/>')
$templateDiv.attr('id','adminTemplates').hide().appendTo('body');var result=$templateDiv.load('//www.zoovy.com/biz/ajax/zmvc/201211/admin_templates.html',function(response,status,xhr){if(status=="error"){r=false;alert('An error occured while trying to load the admin templates.');}
else{$templateDiv.children().each(function(){var id=false;if(id=$(this).attr('id')){}
else if($(this).is('table')){id=$(this).find("tr:first").attr('id')}
else if(id=$(this).children(":first").attr('id')){}
if(id){myControl.templates[id]=$('#'+id).clone();$(this).empty().remove();}})}});return r;},onError:function(d){}},handleElasticFinderResults:{onSuccess:function(tagObj){myControl.util.dump("BEGIN admin.callbacks.handleElasticFinderResults.onSuccess.");var L=myControl.data[tagObj.datapointer]['_count'];myControl.util.dump(" -> Number Results: "+L);$parent=$('#'+tagObj.parentID).empty().removeClass('loadingBG')
if(L==0){$parent.append("Your query returned zero results.");}
else{var pid;for(var i=0;i<L;i+=1){pid=myControl.data[tagObj.datapointer].hits.hits[i]['_id'];$parent.append(myControl.renderFunctions.transmogrify({'id':pid,'pid':pid},'adminElasticResult',myControl.data[tagObj.datapointer].hits.hits[i]['_source']));}
myControl.ext.admin.util.filterFinderResults();}},onError:function(responseData,uuid){myControl.util.handleErrors(responseData,uuid)}},addFinderToDom:{onSuccess:function(tagObj){myControl.ext.admin.util.addFinder(tagObj.targetID,myControl.data[tagObj.datapointer].id);$('#prodFinder').parent().find('.ui-dialog-title').text('Product Finder: '+myControl.data[tagObj.datapointer].pretty);},onError:function(responseData,uuid){myControl.util.dump("BEGIN admin.callback.addFinderToDom.onError");myControl.util.handleErrors(responseData,uuid)
}},addPIDFinderToDom:{onSuccess:function(tagObj){myControl.ext.admin.util.addFinder(tagObj.targetID,tagObj.path,tagObj.datapointer.split('|')[1]);$('#prodFinder').parent().find('.ui-dialog-title').text('Product Finder: '+myControl.data[tagObj.datapointer]['%attribs']['zoovy:prod_name']);},onError:function(d){myControl.util.dump("BEGIN admin.callback.addPIDFinderToDom.onError");$('#'+d['_rtag'].targetID).removeClass('loadingBG').empty().append(myControl.util.getResponseErrors(d)).toggle(true);}},pidFinderChangesSaved:{onSuccess:function(tagObj){myControl.util.dump("BEGIN admin.callbacks.pidFinderChangesSaved");$('#finderMessaging').prepend(myControl.util.formatMessage({'message':'Your changes have been saved.','htmlid':'finderRequestResponse','uiIcon':'check','timeoutFunction':"$('#finderRequestResponse').slideUp(1000);"}))
myControl.ext.admin.util.changeFinderButtonsState('enable');},onError:function(d){$('#finderMessaging').append(myControl.util.getResponseErrors(d)).toggle(true);myControl.ext.admin.util.changeFinderButtonsState('enable');}},finderChangesSaved:{onSuccess:function(tagObj){myControl.util.dump("BEGIN admin.callbacks.finderChangesSaved");var uCount=0;var eCount=0;var eReport='';var $tmp;$('#finderTargetList, #finderRemovedList').find("li[data-status]").each(function(){$tmp=$(this);if($tmp.attr('data-status')=='complete'){uCount+=1;$tmp.removeAttr('data-status');}
else if($tmp.attr('data-status')=='error'){eCount+=1;eReport+="<li>"+$tmp.attr('data-pid')+": "+myControl.data[$tmp.attr('data-pointer')].errmsg+" ("+myControl.data[$tmp.attr('data-pointer')].errid+"<\/li>";}});myControl.util.dump(" -> items updated: "+uCount);myControl.util.dump(" -> errors: "+eCount);if(uCount>0){$('#finderMessaging').prepend(myControl.util.formatMessage({'message':'Items Updated: '+uCount,'htmlid':'finderRequestResponse','uiIcon':'check','timeoutFunction':"$('#finderRequestResponse').slideUp(1000);"}))}
if(eCount>0){$('#finderMessaging').prepend(myControl.util.formatMessage(eCount+' errors occured!<ul>'+eReport+'<\/ul>'));}
myControl.ext.admin.util.changeFinderButtonsState('enable');},onError:function(d){$('#finderMessaging').append(myControl.util.getResponseErrors(d)).toggle(true);myControl.ext.admin.util.changeFinderButtonsState('enable');}},showProdlist:{onSuccess:function(tagObj){myControl.util.dump("BEGIN admin.callbacks.showProdlist");if($.isEmptyObject(myControl.data[tagObj.datapointer]['@products'])){$('#'+tagObj.parentID).empty().removeClass('loadingBG').append('Your search returned zero results');}
else{myControl.util.dump(" -> parentID: "+tagObj.parentID);myControl.util.dump(" -> datapointer: "+tagObj.datapointer);var numRequests=myControl.ext.store_prodlist.util.buildProductList({"templateID":"adminProdStdForList","parentID":tagObj.parentID,"items_per_page":100,"csv":myControl.data[tagObj.datapointer]['@products']});if(numRequests)
myControl.model.dispatchThis();}},onError:function(responseData,uuid){myControl.util.dump('BEGIN admin.callbacks.showProdlist.onError');myControl.util.handleErrors(responseData,uuid);}},finderProductUpdate:{onSuccess:function(tagObj){var tmp=tagObj.datapointer.split('|');var targetID=tmp[0]=='adminNavcatProductInsert'?"finderTargetList":"finderRemovedList";targetID+="_"+tmp[2];$('#'+targetID).attr('data-status','complete');},onError:function(d){var tmp=myControl.data[tagObj.datapointer].split('|');var targetID=tmp[0]=='adminNavcatProductInsert'?"finderTargetList":"finderRemovedList";targetID+="_"+tmp[2];$('#'+targetID).attr({'data-status':'error','data-pointer':tagObj.datapointer});}},filterFinderSearchResults:{onSuccess:function(tagObj){var safePath=myControl.util.makeSafeHTMLId(tagObj.path);var $tmp;$results=$('#finderSearchResults');$results.find('li').each(function(){$tmp=$(this);if($('#finderTargetList_'+$tmp.attr('data-pid')).length>0){$tmp.addClass('ui-state-disabled');}})},onError:function(responseData,uuid){myControl.util.handleErrors(responseData,uuid);}}},validate:{},renderFormats:{elastimage1URL:function($tag,data){$tag.attr('src',myControl.util.makeImage({"name":data.value[0],"w":50,"h":50,"b":"FFFFFF","tag":0}));}},action:{addFinderTo:function(targetID,path,sku){if(sku){myControl.ext.store_product.calls.appProductGet.init(sku,{"callback":"addPIDFinderToDom","extension":"admin","targetID":targetID,"path":path})}
else{myControl.ext.store_navcats.calls.appCategoryDetail.init(path,{"callback":"addFinderToDom","extension":"admin","targetID":targetID})}
myControl.model.dispatchThis();},showFinderInModal:function(path,sku){var $finderModal=$('#prodFinder')
if($finderModal.length>0){$finderModal.empty();}
else{$finderModal=$('<div \/>').attr({'id':'prodFinder','title':'Product Finder'}).appendTo('body');}
if(sku){$finderModal.attr('data-sku',sku)}
else{$finderModal.removeAttr('data-sku')}
$finderModal.attr({'data-path':path}).dialog({modal:true,width:'94%',height:650});this.addFinderTo('prodFinder',path,sku);}},util:{saveFinderChanges:function(){myControl.util.dump("BEGIN admin.util.saveFinderChanges");var myArray=new Array();var $tmp;var $finderModal=$('#prodFinder')
var path=$finderModal.attr('data-path');var sku=$finderModal.attr('data-sku');myControl.util.dump(" -> path: "+path);myControl.util.dump(" -> sku: "+sku);if(sku){var list='';var attribute=myControl.renderFunctions.parseDataVar(path);$('#finderTargetList').find("li").each(function(index){if($(this).attr('data-pid')){list+=','+$(this).attr('data-pid')}});if(list.charAt(0)==','){list=list.substr(1)}
myControl.util.dump(" -> "+attribute+" = "+list);var attribObj={};attribObj[attribute]=list;myControl.ext.admin.calls.product.adminProductUpdate.init(sku,attribObj,{'callback':'pidFinderChangesSaved','extension':'admin'});myControl.ext.admin.calls.product.appProductGetNoLocal.init(sku,{},'immutable');}
else{$('#finderTargetList, #finderRemovedList').find("li").each(function(index){$tmp=$(this);if($tmp.attr('data-status')=='changed'){$tmp.attr('data-status','queued')
myControl.ext.admin.calls.finder.adminNavcatProductInsert.init($tmp.attr('data-pid'),index,path,{"callback":"finderProductUpdate","extension":"admin"});}
else if($tmp.attr('data-status')=='remove'){myControl.ext.admin.calls.finder.adminNavcatProductDelete.init($tmp.attr('data-pid'),path,{"callback":"finderProductUpdate","extension":"admin"});$tmp.attr('data-status','queued')}
else{}});myControl.ext.admin.calls.navcats.appCategoryDetailNoLocal.init(path,{"callback":"finderChangesSaved","extension":"admin"},'immutable');}
},removePidFromFinder:function($listItem){var path=$listItem.closest('[data-path]').attr('data-path');var newLiID='finderRemovedList_'+$listItem.attr('data-pid');if($('#'+newLiID).length>0){$('#'+newLiID).attr('data-status','remove');}
else{var $copy=$listItem.clone();$copy.attr({'id':newLiID,'data-status':'remove'}).appendTo('#finderRemovedList');}
$listItem.empty().remove();},addFinder:function(targetID,path,pid){myControl.util.dump("BEGIN admin.util.addFinder");var safePath=myControl.util.makeSafeHTMLId(path);myControl.util.dump(" -> safePath: "+safePath);var prodlist=new Array();$target=$('#'+targetID).empty();$target.append(myControl.renderFunctions.createTemplateInstance('adminProductFinder',"productFinder_"+myControl.util.makeSafeHTMLId(path)));if(pid){myControl.renderFunctions.translateTemplate(myControl.data['appProductGet|'+pid],"productFinder_"+safePath);var attribute=myControl.renderFunctions.parseDataVar(path);myControl.util.dump(" -> ATTRIBUTE: "+attribute);if(myControl.data['appProductGet|'+pid]['%attribs'][attribute])
prodlist=myControl.data['appProductGet|'+pid]['%attribs'][attribute].split(',');}
else{myControl.util.dump(" -> NON product attribute (no pid specified)");myControl.renderFunctions.translateTemplate(myControl.data['appCategoryDetail|'+path],"productFinder_"+safePath);prodlist=myControl.data['appCategoryDetail|'+path]['@products'];}
var numRequests=myControl.ext.store_prodlist.util.buildProductList({"templateID":prodlist.length<200?"adminProdStdForList":"adminProdSimpleForList","items_per_page":500,"hide_multipage":true,"parentID":"finderTargetList","csv":prodlist});if(numRequests)
myControl.model.dispatchThis();$("#finderTargetList , #finderSearchResults").sortable({connectWith:".connectedSortable",items:"li:not(.ui-state-disabled)",handle:".handle",stop:function(event,ui){var parent=ui.item.parent().attr('id')
if(parent=='finderTargetList'){ui.item.attr({'data-status':'changed','id':'finderTargetList_'+ui.item.attr('data-pid')});}}});$("#finderSearchResults").selectable({filter:'li',filter:"li:not(.ui-state-disabled)"});$("#finderTargetList").sortable("option","containment",'parent');$('#productFinder_'+safePath+' [data-finderAction]').each(function(){myControl.ext.admin.util.bindFinderButtons($(this),safePath);});$('#finderSearchForm').submit(function(event){myControl.ext.admin.util.handleFinderSearch();event.preventDefault();return false})},whichTagsAreChecked:function(idprefix){var r=new Array();var L=myControl.ext.admin.vars.tags.length;for(var i=0;i<L;i+=1){if($('#'+idprefix+myControl.ext.admin.vars.tags[i]).is(':checked')){r.push(myControl.ext.admin.vars.tags[i])};}
return r;},tagsAsCheckboxes:function(idprefix){var r='';var L=myControl.ext.admin.vars.tags;for(var i=0;i<L;i+=1){r+="<div><input type='checkbox' id='finderSearchFilter_"+myControl.ext.admin.vars.tags[i]+"' name='"+myControl.ext.admin.vars.tags[i]+"' /><label for='finderSearchFilter_"+myControl.ext.admin.vars.tags[i]+"'>"+myControl.ext.admin.vars.tags[i].toLowerCase()+"</label></div>"}
return r;},handleFinderSearch:function(){$('#finderSearchResults').empty().addClass('loadingBG');var qObj={};var columnValue=$('#finderSearchQuery').val();qObj.type='product';qObj.mode='elastic-native';qObj.size=400;qObj.query={"query_string":{"query":columnValue}};myControl.ext.store_search.calls.appPublicSearch.init(qObj,{"callback":"handleElasticFinderResults","extension":"admin","parentID":"finderSearchResults","datapointer":"elasticsearch"});myControl.model.dispatchThis();},filterFinderResults:function(){var $tmp;$results=$('#finderSearchResults');$results.find('li').each(function(){$tmp=$(this);if($('#finderTargetList_'+$tmp.attr('data-pid')).length>0){$tmp.addClass('ui-state-disabled');}})},changeFinderButtonsState:function(state){$dom=$('#prodFinder [data-finderaction]')
if(state=='enable'){$dom.removeAttr('disabled').removeClass('ui-state-disabled')}
else if(state=='disable'){$dom.attr('disabled','disabled').addClass('ui-state-disabled');}
else{}},bindFinderButtons:function($button,safePath){if($button.attr('data-finderAction')=='save'){$button.click(function(event){event.preventDefault();myControl.ext.admin.util.saveFinderChanges($button.attr('data-path'));myControl.model.dispatchThis('immutable');myControl.ext.admin.util.changeFinderButtonsState('disable');return false;});}
else if($button.attr('data-finderAction')=='moveToTop'||$button.attr('data-finderAction')=='moveToBottom'){$button.click(function(event){event.preventDefault();$('#finderSearchResults .ui-selected').each(function(){var $copy=$(this).clone();myControl.util.dump(" -> moving item "+$copy.attr('data-pid'));if($button.attr('data-finderAction')=='moveToTop')
$copy.prependTo('#finderTargetList')
else
$copy.appendTo('#finderTargetList')
$copy.attr('data-status','changed');$copy.removeClass('ui-selected').attr('id','finderTargetList_'+$copy.attr('data-pid'));$(this).remove();})
return false;})}
else{}}}}
return r;}