handlePogs=function(v,o){this.initialize(v,o);}
$.extend(handlePogs.prototype,{initialize:function(pogs,o){this.pogs=pogs;this.invCheck=o.invCheck?o.invCheck:false;this.imgClassName=o.imgClassName?o.imgClassName:'sogImage';this.sku=o.sku;this.handlers={};this.addHandler("type","text","renderOptionTEXT");this.addHandler("type","radio","renderOptionRADIO");this.addHandler("type","select","renderOptionSELECT");this.addHandler("type","imgselect","renderOptionIMGSELECT");this.addHandler("type","number","renderOptionNUMBER");this.addHandler("type","cb","renderOptionCB");this.addHandler("type","attribs","renderOptionATTRIBS");this.addHandler("type","readonly","renderOptionREADONLY");this.addHandler("type","hidden","renderOptionHIDDEN");this.addHandler("type","assembly","renderOptionHIDDEN");this.addHandler("type","textarea","renderOptionTEXTAREA");this.addHandler("type","imggrid","renderOptionIMGGRID");this.addHandler("type","calendar","renderOptionCALENDAR");this.addHandler("type","biglist","renderOptionBIGLIST");this.addHandler("unknown","","renderOptionUNKNOWN");},addHandler:function(key,value,f){this.handlers[key+"."+value]=f;},listOptionIDs:function(){var r=Array();for(var i=0,len=this.pogs.length;i<len;++i){r.push(this.pogs[i].id);}
return(r);},getOptionByID:function(id){var r=null;for(var i=0,len=this.pogs.length;i<len;++i){if(this.pogs[i].id==id){r=this.pogs[i];}}
return(r);},renderOptionSELECT:function(pog,safeid){var pogid=pog.id;var $parentDiv=$("<span \/>");var $selectList=$("<select>").attr({"id":"pog_"+safeid,"name":"pog_"+pogid}).addClass('zform_select');var i=0;var len=pog.options.length;var selOption;var optionTxt;if(len>0){optionTxt=(pog['optional']==1)?"":"Please choose (required)";selOption="<option value='' disable='disabled' selected='selected'>"+optionTxt+"<\/option>";$selectList.append(selOption);}
while(i<len){optionTxt=pog['options'][i]['prompt'];if(pog['options'][i]['p'])
optionTxt+=pogs.handlePogPrice(pog['options'][i]['p']);selOption="<option value='"+pog['options'][i]['v']+"' id='option_"+pogid+""+pog['options'][i]['v']+"'>"+optionTxt+"<\/option>";$selectList.append(selOption);i++;}
$selectList.appendTo($parentDiv);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionBIGLIST:function(pog,safeid){var pogid=pog.id;var selOptions='';var lastOptGrp,selValues;var inc=0;var len=pog.options.length;var $parentDiv=$("<span \/>");var $selectList=$("<select \/>").attr({"id":"pog_"+safeid,"name":"pog_"+pogid}).addClass("zform_select zform_biglist");$selectList.append("<option value='' disable='disabled' selected='selected'>Please Choose...<\/option>");selValues=pog['options'][inc]['prompt'].split('|');lastOptGrp=selValues[0];selOptions+="<optgroup label='"+selValues[0]+"'>";while(inc<len){selValues=pog['options'][inc]['prompt'].split('|');optGrp=selValues[0];if(optGrp!=lastOptGrp){selOptions+="<\/optgroup><optgroup label='"+selValues[0]+"'>";}
selOptions+="<option value='"+pog['options'][inc]['v']+"'>"+selValues[1]+"<\/option>\n";lastOptGrp=selValues[0]
inc+=1;}
selOptions+="<\/optgroup>";$selectList.append(selOptions).appendTo($parentDiv);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionIMGSELECT:function(pog,safeid){var pogid=pog.id;var $parentDiv=$("<span \/>");var $selectList=$("<select>").attr({"id":"pog_"+safeid,"name":"pog_"+pogid}).addClass('zform_select').bind('change',function(e){var thumbnail=$("#pog_"+safeid+" option:selected").attr('data-thumbnail');$("#selectImg_"+safeid).attr('src',myControl.util.makeImage({"w":pog.width,"h":pog.height,"name":thumbnail,"b":"FFFFFF","tag":false,"lib":myControl.username,"id":"selectImg_"+safeid}));});var i=0;var len=pog.options.length;var selOption;var optionTxt;if(len>0){optionTxt=(pog['optional']==1)?"":"Please choose (required)";selOption="<option value='' disabled='disabled' selected='selected'>"+optionTxt+"<\/option>";$selectList.append(selOption);}
while(i<len){optionTxt=pog['options'][i]['prompt'];if(pog['options'][i]['p'])
optionTxt+=pogs.handlePogPrice(pog['options'][i]['p']);selOption="<option value='"+pog['options'][i]['v']+"' data-thumbnail='"+pog['options'][i]['img']+"' id='option_"+pogid+""+pog['options'][i]['v']+"'>"+optionTxt+"<\/option>";$selectList.append(selOption);i++;}
$selectList.appendTo($parentDiv);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
$imageDiv=$('<div>').attr({"id":"imgSelect_"+safeid+"_img"}).addClass('imageselect_image');$imageDiv.html(myControl.util.makeImage({"w":pog.width,"h":pog.height,"name":"blank.gif","b":"FFFFFF","tag":true,"lib":myControl.username,"id":"selectImg_"+pogid}));$imageDiv.appendTo($parentDiv);return $parentDiv;myControl.util.dump('END renderOptionIMGSELECT for pog '+pog.id);},renderOptionRADIO:function(pog,safeid){var pogid=pog.id;var $parentDiv=$("<span \/>");if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
var $radioInput;var radioLabel;var i=0;var len=pog['options'].length;while(i<len){radioLabel="<label for='pog_id_"+safeid+"_value_"+pog['options'][i]['v']+"'>"+pog['options'][i]['prompt']+"<\/label>";$radioInput=$('<input>').attr({type:"radio",name:"pog_"+pogid,value:pog['options'][i]['v'],id:"pog_id_"+safeid+"_value_"+pog['options'][i]['v']});$parentDiv.append($radioInput).append(radioLabel);i++}
return $parentDiv;},renderOptionCB:function(pog,safeid){var pogid=pog.id;var $parentDiv=$("<span \/>");var $checkbox=$('<input>').attr({type:"checkbox",name:"pog_"+pogid,value:'ON',id:"pog_"+safeid});var $hidden=$('<input>').attr({type:"hidden",name:"pog_"+pogid+"_cb",value:'1',id:"pog_"+safeid});$parentDiv.append($checkbox).append($hidden);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionHIDDEN:function(pog,safeid){var pogid=pog.id;var defaultValue=myControl.util.isSet(pog['default'])?pog['default']:"";var $parentDiv=$("<span \/>");var $hidden=$('<input>').attr({type:"hidden",name:"pog_"+pogid,value:defaultValue,id:"pog_"+safeid});$parentDiv.append($hidden);return $parentDiv;},renderOptionATTRIBS:function(pog,safeid){},renderOptionTEXT:function(pog,safeid){var pogid=pog.id;var defaultValue=myControl.util.isSet(pog['default'])?pog['default']:"";var $parentDiv=$("<span \/>");var $textbox=$('<input>').attr({type:"text",name:"pog_"+pogid,value:defaultValue,id:"pog_"+safeid}).addClass('zform_textbox')
if(pog['maxlength']){$textbox.keyup(function(){if(this.value.length>(pog['maxlength']-1))
this.value=this.value.substring(0,pog['maxlength']);});}
$parentDiv.append($textbox);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionCALENDAR:function(pog,safeid){var pogid=pog.id;var defaultValue=myControl.util.isSet(pog['default'])?pog['default']:"";var $parentDiv=$("<span \/>");var $textbox=$('<input>').attr({type:"text",name:"pog_"+pogid,value:defaultValue,id:"pog_"+safeid}).addClass('zform_textbox').datepicker({altFormat:"DD, d MM, yy"});$parentDiv.append($textbox);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
if(pog.rush_prompt){$parentDiv.append("<div class='zhint' id='rush_prompt_"+safeid+">"+pog['rush_prompt']+"<\/div>");}
return $parentDiv;},renderOptionNUMBER:function(pog,safeid){var pogid=pog.id;var defaultValue=myControl.util.isSet(pog['default'])?pog['default']:"";var $parentDiv=$("<span \/>");var $textbox=$('<input>').attr({type:"number",name:"pog_"+pogid,value:defaultValue,id:"pog_"+safeid}).addClass('zform_textbox').keyup(function(){this.value=this.value.replace(/[^0-9]/g,'');});if(pog['max'])
$textbox.attr('max',pog['max']);if(pog['min'])
$textbox.attr('max',pog['max']);$parentDiv.append($textbox);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionTEXTAREA:function(pog,safeid){var pogid=pog.id;var defaultValue=myControl.util.isSet(pog['default'])?pog['default']:"";var $parentDiv=$("<span \/>");var $textbox=$('<textarea>').attr({name:"pog_"+pogid,value:defaultValue,id:"pog_"+safeid}).addClass('zform_textarea');$parentDiv.append($textbox);if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
return $parentDiv;},renderOptionREADONLY:function(pog,safeid){return $("<span class='zsmall'>"+pog['default']+"<\/span>");},renderOptionIMGGRID:function(pog,safeid){var pogid=pog.id;var $parentDiv=$("<span \/>");if(pog['ghint']){$parentDiv.append(pogs.showHintIcon(pogid,pog['ghint']))}
var $radioInput;var radioLabel;var thumbnail;var i=0;var len=pog['options'].length;while(i<len){thumbnail=myControl.util.makeImage({"w":pog.width,"h":pog.height,"name":pog['options'][i]['img'],"b":"FFFFFF","tag":true,"lib":myControl.username,"id":"selectImg_"+safeid});radioLabel="<label for='pog_id_"+safeid+"_value_"+pog['options'][i]['v']+"'>"+pog['options'][i]['prompt']+"<\/label>";$radioInput=$('<input>').attr({type:"radio",name:"pog_"+pogid,value:pog['options'][i]['v'],id:"pog_id_"+safeid+"_value_"+pog['options'][i]['v']});$parentDiv.append(thumbnail).append($radioInput).append(radioLabel).wrap("<div class='floatLeft'><\/div>");;i++}
return $parentDiv;},renderOptionUNKNOWN:function(pog,safeid){return("UNKNOWN "+pog.type+": "+pog.prompt+" / "+pog.id);},showHintIcon:function(pogid,pogHint){myControl.util.dump("BEGIN variations.showHintIcon");return"<span class='ghint_qmark_container'><a href='#' onclick='$(\"#ghint_"+pogid+"\").toggle(); return false;' class='ghint_qmark'>?<\/a></span><div style='display:none;' class='zhint' id='ghint_"+pogid+"'>"+pogHint+"</div>";},handlePogPrice:function(P){var price;if(P.charAt(0)=='+'){price=" +$"+P.substr(1);}
else if(P.charAt(0)=="-")
price=" -$"+P.substr(1);else if(P.charAt(0)=="$")
price=" "+P;else
price=" $"+P;return price;},renderOption:function(pog,pid){var pogid=pog.id;var safeid=myControl.util.makeSafeHTMLId(pogid);var $formFieldDiv=$("<div>").attr("id","div_"+safeid).addClass("zform_div").addClass("pogType_"+pog.type);var $optionObj;var labelTitle=(pog.ghint)?pog.ghint:pog.prompt;var $formFieldLabel=$('<label>').attr({"for":"pog_"+safeid,"id":"pog_"+safeid+"_id","title":labelTitle}).text(pog.prompt);$formFieldDiv.append($formFieldLabel);if(this.handlers["pogid."+pogid]){$optionObj=eval("this."+this.handlers["pogid."+pogid]+"(pog,safeid)");}
else if(this.handlers["type."+pog.type]){$optionObj=eval("this."+this.handlers["type."+pog.type]+"(pog,safeid)");}
else{$optionObj=eval("this."+this.handlers["unknown."]+"(pog,safeid)");}
$formFieldDiv.append($optionObj);return $formFieldDiv;}});