var store_prodlist=function(){var r={vars:{forgetmeContainer:{}},calls:{appProductGet:{init:function(obj,tagObj,Q){var r=0;var pid=obj.pid
tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj["datapointer"]="appProductGet|"+pid;if(myControl.model.fetchData('appProductGet|'+pid)==false){r=2;this.dispatch(pid,tagObj,Q);}
else{myControl.util.handleCallback(tagObj)}
return r;},dispatch:function(pid,tagObj,Q){var obj={};obj["_cmd"]="appProductGet";obj["pid"]=pid;obj["_tag"]=tagObj;myControl.model.addDispatchToQ(obj,Q);}},getDetailedProduct:{init:function(obj,tagObj,Q){var r=0;tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj["datapointer"]="appProductGet|"+obj.pid;if(myControl.model.fetchData(tagObj.datapointer)==false){r+=1;}
else if(obj['withInventory']&&typeof myControl.data[tagObj.datapointer]['@inventory']=='undefined'){r+=1;}
else if(obj['withVariations']&&typeof myControl.data[tagObj.datapointer]['@variations']=='undefined'){r+=1;}
if(obj['withReviews']&&myControl.model.addDispatchToQ(obj,Q)){r+=1;}
if(r==0){myControl.util.handleCallback(tagObj)}
else{this.dispatch(obj,tagObj,Q)}
return r;},dispatch:function(obj,tagObj,Q){myControl.ext.store_prodlist.calls.appReviewsList.init(obj.pid,{},Q);obj["_cmd"]="appProductGet";obj["_tag"]=tagObj;myControl.model.addDispatchToQ(obj,Q);}},appReviewsList:{init:function(pid,tagObj,Q){var r=0;tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj["datapointer"]="appReviewsList|"+pid;if(myControl.model.fetchData('appReviewsList|'+pid)==false){r=1;this.dispatch(pid,tagObj,Q)}
else{myControl.util.handleCallback(tagObj)}
return r;},dispatch:function(pid,tagObj,Q){myControl.model.addDispatchToQ({"_cmd":"appReviewsList","pid":pid,"_tag":tagObj},Q);}}},callbacks:{init:{onSuccess:function(){return true;},onError:function(){myControl.util.dump('BEGIN myControl.ext.store_prodlist.callbacks.init.onError');}},translateTemplate:{onSuccess:function(tagObj){myControl.renderFunctions.translateTemplate(myControl.data[tagObj.datapointer],tagObj.parentID);},onError:function(responseData,uuid){myControl.util.handleErrors(responseData,uuid)}},handleForgetmeList:{onSuccess:function(tagObj){var L=myControl.data['getCustomerList|forgetme']['@forgetme'].length
myControl.ext.store_prodlist.vars.forgetmeContainer.csv=[];for(i=0;i<L;i+=1){myControl.ext.store_prodlist.vars.forgetmeContainer.csv.push(myControl.data['getCustomerList|forgetme']['@forgetme'][i].SKU)}},onError:function(responseData,uuid){myControl.util.handleErrors(responseData,uuid)}}},renderFormats:{mpPagesAsListItems:function($tag,data){var o='';for(i=1;i<=data.value;i+=1){o+="<li class='mpControlJumpToPage' data-page='"+i+"'><span>page: "+i+"<\/span><\/li>";}
$tag.append(o);},addToCartButton:function($tag,data){var pid=data.bindData.cleanValue;var showATC=true;$tag.attr('id',$tag.attr('id')+'_'+pid).addClass('atcButton').before("<div class='atcSuccessMessage' id='atcMessaging_"+pid+"'><\/div>");if(myControl.ext.store_product.util.productIsPurchaseable(pid)){$tag.show().removeClass('displayNone').removeAttr('disabled');if(typeof myControl.data['appProductGet|'+pid]['@variations']=='undefined'){showATC=false}
else if(!$.isEmptyObject(myControl.data['appProductGet|'+pid]['@variations'])){showATC=false}
if(showATC){$tag.addClass('addToCartButton').unbind('.myATCEvent').bind('click.myATCEvent',function(event){$(this).parent().submit();event.preventDefault();}).text('Add To Cart')}
else{$tag.addClass('chooseOptionsButton').unbind('.myATCEvent').bind('click.myATCEvent',function(event){event.preventDefault();myControl.ext.myRIA.util.handlePageContent('product',pid)}).text('Choose Options')}}
else{$tag.replaceWith("<span class='notAvailable'>not available</span>");}
}},util:{getProductDataForList:function(csv,parentID){myControl.util.dump("BEGIN myControl.ext.store_prodlist.util.getProductDataForList");var $parent=$('#'+parentID).removeClass('loadingBG');var numRequests=0;var L=csv.length;var call='appProductGet'
if(myControl.ext.store_prodlist.vars[parentID].withVariations+myControl.ext.store_prodlist.vars[parentID].withInventory+myControl.ext.store_prodlist.vars[parentID].withReviews>0){call='getDetailedProduct'}
for(var i=0;i<L;i+=1){$parent.append(myControl.renderFunctions.createTemplateInstance(myControl.ext.store_prodlist.vars[parentID].templateID,{"id":parentID+"_"+csv[i],"pid":csv[i]}));numRequests+=myControl.ext.store_prodlist.calls[call].init({"pid":csv[i],"withVariations":myControl.ext.store_prodlist.vars[parentID].withVariations,"withReviews":myControl.ext.store_prodlist.vars[parentID].withReviews,"withInventory":myControl.ext.store_prodlist.vars[parentID].withInventory},parentID?{'callback':'translateTemplate','extension':'store_prodlist','parentID':parentID+"_"+csv[i]}:{});}
return numRequests;},getProductDataForLaterUse:function(csv){var L=csv.length;for(var i=0;i<L;i+=1){if(myControl.util.isSet(csv[i])){myControl.ext.store_prodlist.calls.appProductGet.init(csv[i],{},'passive')};}},filterProdlist:function(csvArray){var L=csvArray.length;var rArray=new Array();for(i=0;i<L;i+=1){if(myControl.util.isSet(csvArray[i])&&$.inArray(csvArray[i],myControl.ext.store_prodlist.vars.forgetmeContainer.csv<0)){rArray.push(csvArray[i]);}}
return rArray;},setProdlistVars:function(paramObj){var r=true;if(paramObj.parentID&&paramObj.templateID){myControl.ext.store_prodlist.vars[paramObj.parentID]=typeof myControl.ext.store_prodlist.vars[paramObj.parentID]==='object'?myControl.ext.store_prodlist.vars[paramObj.parentID]:{};var csvArray=new Array();if(typeof paramObj.csv==='undefined'){r=false;myControl.util.dump(" -> attempted to make a product list, but no product received.");}
else{if(typeof paramObj.csv==='object'){csvArray=paramObj.csv;}
else if(typeof paramObj.csv==='string'){csvArray=paramObj.csv.split(',')}
else{r=false;myControl.util.dump(" -> unknown data type for csv. csv type = "+typeof csv+" paramObj.csv type = "+typeof paramObj.csv);}}
csvArray=$.grep(csvArray,function(n){return(n);});var L=csvArray.length;csvArray=myControl.ext.store_prodlist.util.filterProdlist(csvArray);var itemsRemoved=L-csvArray.length;if(L==0){r=false;}
if(r){var itemsPerPage;if(paramObj.items_per_page){itemsPerPage=paramObj.items_per_page}
else if(myControl.ext.store_prodlist.vars[paramObj.parentID]&&myControl.ext.store_prodlist.vars[paramObj.parentID].items_per_page){itemsPerPage=myControl.ext.store_prodlist.vars[paramObj.parentID].items_per_page}
else{itemsPerPage=L}
var page=paramObj.page_in_focus?paramObj.page_in_focus*1:1;var startpoint=(page-1)*itemsPerPage;var endpoint=startpoint+itemsPerPage;var hideMultipage=myControl.ext.store_prodlist.vars[paramObj.parentID].hide_multipage;endpoint=endpoint>L?L:endpoint;myControl.ext.store_prodlist.vars[paramObj.parentID]={"csv":csvArray,"templateID":paramObj.templateID,"parentID":paramObj.parentID,"hide_multipage":hideMultipage,"withInventory":paramObj.withInventory?paramObj.withInventory:0,"withVariations":paramObj.withVariations?paramObj.withVariations:0,"withReviews":paramObj.withReviews?paramObj.withReviews:0,"page_start_point":startpoint+1,"page_end_point":endpoint,"page_in_focus":page,"page_product_count":endpoint-startpoint,"items_per_page":itemsPerPage,"items_on_this_page":csvArray.slice(startpoint,endpoint).length,"items_removed":itemsRemoved,"total_product_count":L,"total_page_count":Math.ceil(L/itemsPerPage)};}
else{myControl.util.dump(" -> Either an issue with the product data or the list is empty.");}}
else{myControl.util.dump(" -> Missing some required fields for setProdlistVars");r=false;}
return r;},buildProductList:function(paramObj){var r=0;if(myControl.ext.store_prodlist.util.setProdlistVars(paramObj)){r=myControl.ext.store_prodlist.util.handleProductList(paramObj.parentID);}
else{$('#'+paramObj.parentID).removeClass('loadingBG');}
return r;},handleProductList:function(parentID){var r=0;var $parent=$('#'+parentID).empty();var csvArray=new Array();if(myControl.ext.store_prodlist.vars[parentID].items_per_page>=myControl.ext.store_prodlist.vars[parentID].csv.length){csvArray=myControl.ext.store_prodlist.vars[parentID].csv}
else{csvArray=myControl.ext.store_prodlist.vars[parentID].csv.slice(myControl.ext.store_prodlist.vars[parentID].page_start_point-1,myControl.ext.store_prodlist.vars[parentID].page_end_point);if(!myControl.ext.store_prodlist.vars[parentID].hide_multipage){this.showMPControls(parentID);}}
r=myControl.ext.store_prodlist.util.getProductDataForList(csvArray,parentID);return r;},mpJumpToPage:function(parentID,page){myControl.ext.store_prodlist.vars[parentID].page_in_focus=page;myControl.ext.store_prodlist.util.setProdlistVars(myControl.ext.store_prodlist.vars[parentID]);if(myControl.ext.store_prodlist.util.handleProductList(parentID)){myControl.model.dispatchThis()}},showMPControls:function(parentID){var $parent=$('#'+parentID);$('#mpControl_'+parentID).empty().remove();$parent.before(myControl.renderFunctions.createTemplateInstance('mpControlSpec','mpControl_'+parentID));myControl.renderFunctions.translateTemplate(myControl.ext.store_prodlist.vars[parentID],'mpControl_'+parentID);$parent.parent().find('.mpControlJumpToPage').click(function(){myControl.ext.store_prodlist.util.mpJumpToPage(parentID,$(this).attr('data-page'))})
$parent.parent().find('.paging').each(function(){$this=$(this)
if($this.attr('data-role')=='next'){if(myControl.ext.store_prodlist.vars[parentID].page_in_focus==myControl.ext.store_prodlist.vars[parentID].total_page_count){$this.attr('disabled','disabled').addClass('ui-state-disabled')}
else{$(this).click(function(){myControl.ext.store_prodlist.util.mpJumpToPage(parentID,myControl.ext.store_prodlist.vars[parentID].page_in_focus+1)})}}
else if($this.attr('data-role')=='previous'){if(myControl.ext.store_prodlist.vars[parentID].page_in_focus==1){$this.attr('disabled','disabled').addClass('ui-state-disabled')}
else{$(this).click(function(){myControl.ext.store_prodlist.util.mpJumpToPage(parentID,myControl.ext.store_prodlist.vars[parentID].page_in_focus-1)})}}});}}}
return r;}