var store_search=function(){var r={vars:{"ajaxRequest":{}},calls:{searchResult:{init:function(frmObj,tagObj){var r=0;var keywords=$.trim(frmObj.KEYWORDS);tagObj=typeof tagObj!='object'?{}:tagObj;var myTagObj={};myTagObj=$.extend(myTagObj,tagObj);myTagObj.datapointer="searchResult|"+keywords;if(myControl.model.fetchData(myTagObj.datapointer)==false){r+=1;this.dispatch(frmObj,myTagObj)}
else{myControl.util.handleCallback(myTagObj)}
return r;},dispatch:function(frmObj,myTagObj){frmObj['_cmd']="searchResult";frmObj['_tag']=myTagObj;myControl.model.addDispatchToQ(frmObj);}},appPublicSearch:{init:function(obj,tagObj,Q){myControl.util.dump("BEGIN myControl.ext.store_search.calls.appPublicSearch");this.dispatch(obj,tagObj)
return 1;},dispatch:function(obj,tagObj,Q){obj['_cmd']="appPublicSearch";obj['_tag']=tagObj;myControl.model.addDispatchToQ(obj,Q);}}},callbacks:{init:{onSuccess:function(){var r=true;return r;},onError:function(){myControl.util.dump('BEGIN myControl.ext.store_navcats.callbacks.init.onError');}}},util:{getAlternativeQueries:function(keywords,tagObj){var keywordsArray=new Array();keywordsArray=keywords.split(' ');var permutations=this.getPermutationsOfArray(keywordsArray);var L=permutations.length;var mode=$('#headerModeInput').val();var catalog=$('#headerCatalog').val();var thisKeyword;for(var i=0;i<L;i+=1){thisKeyword=this.getPermArrayIntoString(permutations[i]);myControl.ext.store_search.calls.searchResult.init({"KEYWORDS":thisKeyword,"CATALOG":catalog,"MODE":mode},tagObj);}},getPermArrayIntoString:function(a){var r='';for(var i=0;i<a.length;i+=1){r+=a[i]+' ';}
return r;},getPermutationsOfArray:function(keywordsArray){var combine=function(a){var fn=function(n,src,got,all){if(n==0){if(got.length>0){all[all.length]=got;}
return;}
for(var j=0;j<src.length;j++){fn(n-1,src.slice(j+1),got.concat([src[j]]),all);}
return;}
var all=[];for(var i=0;i<a.length;i++){fn(i,a,[],all);}
all.push(a);return all;}
return combine(keywordsArray);},bindKeywordAutoComplete:function(formID){var $keywordInput=$('#'+formID+' input[name*="KEYWORDS"]');var $catalogInput=$('#'+formID+' input[name*="CATALOG"]');$keywordInput.autocomplete({source:function(request,response){if(!$.isEmptyObject(myControl.ext.store_search.vars.ajaxRequest)){myControl.ext.store_search.vars.ajaxRequest.abort();}
myControl.ext.store_search.vars.ajaxRequest=$.ajax({type:"GET",url:myControl.vars.jqurl+"?_cmd=getKeywordAutoComplete&_zjsid="+myControl.sessionId+"&_uuid="+myControl.model.fetchUUID()+"&keywords="+$keywordInput.val()+"&catalog="+$catalogInput.val(),context:this,dataType:"json",complete:function(){myControl.ext.store_search.vars.ajaxRequest={};},success:function(data){response($.map(data['@result'],function(item){return{label:item[0]+" ( "+item[1]+" items )",value:item[0]}}));}});},minLength:2,select:function(event,ui){$keywordInput.val(ui.item.value);$('#'+formID).submit();}});}}}
return r;}