var store_cart=function(){var r={vars:{"cartAccessories":[]},calls:{cartItemsList:{init:function(tagObj){var r=0;tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj.datapointer="cartItemsList";if(myControl.model.fetchData('cartItemsList')==false){myControl.util.dump(" -> cartItemsList is not local. go get her Ray!");r=1;this.dispatch(tagObj);}
else{myControl.util.handleCallback(tagObj);}
return r;},dispatch:function(tagObj){myControl.model.addDispatchToQ({"_cmd":"cartItemsList","_zjsid":myControl.sessionId,"_tag":tagObj});}},getCartContents:{init:function(tagObj,Q){tagObj=$.isEmptyObject(tagObj)?{}:tagObj;Q=Q?Q:'immutable';tagObj.datapointer="cartItemsList";this.dispatch(tagObj,Q);return 1;},dispatch:function(tagObj,Q){myControl.model.addDispatchToQ({"_cmd":"cartItemsList","_zjsid":myControl.sessionId,"_tag":tagObj},Q);}},cartItemUpdate:{init:function(stid,qty,tagObj){myControl.util.dump('BEGIN myControl.ext.store_cart.calls.cartItemUpdate.');tagObj=$.isEmptyObject(tagObj)?{}:tagObj;var r=0;if(!stid||isNaN(qty)){myControl.util.dump(" -> cartItemUpdate requires both a stid ("+stid+") and a quantity as a number("+qty+")");}
else{r=1;this.dispatch(stid,qty,tagObj);}
return r;},dispatch:function(stid,qty,tagObj){myControl.model.addDispatchToQ({"_cmd":"updateCart","stid":stid,"quantity":qty,"_zjsid":myControl.sessionId,"_tag":tagObj},'immutable');myControl.calls.cartSet.init({'payment-pt':null});}},cartShippingMethods:{init:function(tagObj,Q){var r=0
tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj.datapointer="cartShippingMethods";if(myControl.model.fetchData('cartShippingMethods')==false){myControl.util.dump(" -> cartItemsList is not local. go get her Ray!");r=1;Q=Q?Q:'immutable';this.dispatch(tagObj,Q);}
else{myControl.util.handleCallback(tagObj);}
return r;},dispatch:function(tagObj,Q){myControl.model.addDispatchToQ({"_cmd":"cartShippingMethods","_tag":tagObj},Q);}},cartShippingMethodsWithUpdate:{init:function(tagObj){tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj.datapointer="cartShippingMethods";this.dispatch(tagObj);return 1;},dispatch:function(tagObj){myControl.model.addDispatchToQ({"_cmd":"cartShippingMethods","update":"1","trace":"1","_tag":tagObj},'immutable');}},cartGiftcardAdd:{init:function(giftcard,tagObj){this.dispatch(giftcard,tagObj);return 1;},dispatch:function(giftcard,tagObj){myControl.model.addDispatchToQ({"_cmd":"cartGiftcardAdd","giftcard":giftcard,"_tag":tagObj},'immutable');}},cartCouponAdd:{init:function(coupon,tagObj){this.dispatch(coupon,tagObj);return 1;},dispatch:function(coupon,tagObj){myControl.model.addDispatchToQ({"_cmd":"cartCouponAdd","coupon":coupon,"_tag":tagObj},'immutable');}}},callbacks:{init:{onSuccess:function(){var r=true;return r;},onError:function(){myControl.util.dump('BEGIN myControl.ext.simple_sample.callbacks.init.onError');}},displayCart:{onSuccess:function(tagObj){myControl.util.dump('BEGIN myControl.ext.store_cart.callbacks.displayCart.onSuccess');myControl.ext.store_cart.vars.cartAccessories=myControl.ext.store_cart.util.getCSVOfAccessories();myControl.util.dump(' -> '+tagObj.parentID);myControl.renderFunctions.translateTemplate(myControl.data.cartItemsList.cart,tagObj.parentID);var $parent=$('#'+tagObj.parentID);myControl.ext.store_cart.util.showStuff({"parentID":"cartViewerContents","templateID":"cartViewerProductTemplate"});$('#cartSummaryTotals').append(myControl.renderFunctions.createTemplateInstance('cartSummaryTemplate','cartSummary'));myControl.renderFunctions.translateTemplate(myControl.data.cartItemsList.cart,'cartSummary');},onError:function(d){myControl.util.dump('BEGIN myControl.ext.store_cart.callbacks.displayCart.onError');$('#modalCart').append(myControl.util.getResponseErrors(d)).toggle(true);}},updateCartLineItem:{onSuccess:function(tagObj){myControl.util.dump('BEGIN myControl.ext.store_cart.callbacks.updateCartLineItem.onSuccess');var stid=myControl.ext.store_cart.util.getStuffIndexBySTID($('#'+tagObj.parentID).attr('data-stid'));myControl.util.dump(" -> stid: "+stid);myControl.util.dump(" -> tagObj.parentID: "+tagObj.parentID);myControl.renderFunctions.translateTemplate(myControl.data.cartItemsList.cart.stuff[stid],tagObj.parentID);},onError:function(responseData,uuid){myControl.util.handleErrors(responseData,uuid)}}},renderFormats:{cartItemQty:function($tag,data){var stid=$tag.closest('[data-stid]').attr('data-stid');$tag.val(data.bindData.cleanValue).attr('data-stid',stid);},removeItemBtn:function($tag,data){if(data.value[0]=='%'){$tag.remove()}
else{$tag.click(function(){myControl.ext.store_cart.util.updateCartQty(data.value,0);myControl.model.dispatchThis('immutable');});}},orderBalance:function($tag,data){var o='';var amount=data.bindData.cleanValue;o+=data.bindData.pretext?data.bindData.pretext:'';if(amount*1<=0){o+=data.bindData.currencySign?data.bindData.currencySign:'$';o+='0.00';}
else{o+=myControl.util.formatMoney(amount,data.bindData.currencySign,'',data.bindData.hideZero);}
o+=data.bindData.posttext?data.bindData.posttext:'';$tag.text(o);},shipInfoById:function($tag,data){var o='';var L=myControl.data.cartShippingMethods['@methods'].length;for(var i=0;i<L;i+=1){if(myControl.data.cartShippingMethods['@methods'][i].id==data.value){var pretty=myControl.util.isSet(myControl.data.cartShippingMethods['@methods'][i]['pretty'])?myControl.data.cartShippingMethods['@methods'][i]['pretty']:myControl.data.cartShippingMethods['@methods'][i]['name'];o="<span class='orderShipMethod'>"+pretty+": <\/span>";if(myControl.data.cartShippingMethods['@methods'][i].amount){o+="<span class='orderShipAmount'>"+myControl.util.formatMoney(myControl.data.cartShippingMethods['@methods'][i].amount,' $',2,false)+"<\/span>";}
break;}}
$tag.html(o);},shipMethodsAsRadioButtons:function($tag,data){var o='';var shipName;var L=data.value.length;var id,isSelectedMethod,safeid;for(var i=0;i<L;i+=1){isSelectedMethod=false;safeid=myControl.util.makeSafeHTMLId(data.value[i].id);id=data.value[i].id;if(id==myControl.data.cartItemsList.cart['ship.selected_id']){isSelectedMethod=true;}
shipName=myControl.util.isSet(data.value[i].pretty)?data.value[i].pretty:data.value[i].name
o+="<li class='shipcon "
if(isSelectedMethod)
o+=' selected ';o+="shipcon_"+safeid;o+="'><input type='radio' name='ship.selected_id' id='ship-selected_id_"+safeid+"' value='"+id+"' onClick='myControl.ext.store_cart.util.shipMethodSelected(this.value,\""+safeid+"\"); myControl.model.dispatchThis(\"immutable\"); '";if(isSelectedMethod)
o+=" checked='checked' "
o+="/><label for='ship-selected_id_"+safeid+"'>"+shipName+": <span >"+myControl.util.formatMoney(data.value[i].amount,'$','',false)+"<\/span><\/label><\/li>";}
$tag.html(o);}},util:{showCartInModal:function(templateID){var $parent=$('#modalCart');if($parent.length==0){$parent=$("<div \/>").attr({"id":"modalCart","title":"Your Shopping Cart"}).appendTo(document.body);}
else{$parent.empty();}
$parent.append(myControl.renderFunctions.createTemplateInstance(templateID,"modalCartContents"));var tagObj={"callback":"displayCart","templateID":templateID,"parentID":"modalCartContents","extension":"store_cart"}
if(myControl.ext.store_cart.calls.cartShippingMethods.init({},'immutable')){myControl.calls.refreshCart.init(tagObj,'immutable');}
else{myControl.ext.store_cart.calls.cartItemsList.init(tagObj,'immutable');}
myControl.model.dispatchThis('immutable');$parent.dialog({modal:true,width:'80%',height:$(window).height()-100});},handleGiftcardSubmit:function(v,parentID){myControl.ext.store_cart.calls.cartGiftcardAdd.init(v,{"parentID":parentID,"message":"Giftcard Added!","callback":"showMessaging"});this.updateCartSummary();if(parentID)
$('#'+parentID+' .zMessage').empty().remove();},shipMethodSelected:function(shipID,safeID){myControl.calls.cartSet.init({'ship.selected_id':shipID});myControl.ext.store_cart.calls.cartShippingMethodsWithUpdate.init();this.updateCartSummary();},handleCouponSubmit:function(v,parentID){myControl.ext.store_cart.calls.cartCouponAdd.init(v,{"parentID":parentID,"message":"Coupon Added!","callback":"showMessaging"});this.updateCartSummary();if(parentID)
$('#'+parentID+' .zMessage').empty().remove();},updateCartSummary:function(){$('#cartSummaryTotals').empty().append(myControl.renderFunctions.createTemplateInstance('cartSummaryTemplate','cartSummary'));myControl.ext.store_cart.calls.getCartContents.init({'callback':'translateTemplate','parentID':'cartSummary'},'immutable');},showStuff:function(P){if(!P.parentID||!P.templateID){myControl.util.dump(" -> parentID ("+P.parentID+") and/or TemplateID ("+P.templateID+") blank. both are required.");}
else{var $parent=$('#'+P.parentID);var L=myControl.data.cartItemsList.cart.stuff.length;var stid;myControl.util.dump(" -> items in stuff = "+L);for(var i=0;i<L;i+=1){stid=myControl.data.cartItemsList.cart.stuff[i].stid
$parent.append(myControl.renderFunctions.createTemplateInstance(P.templateID,{"id":"cartViewer_"+stid,"stid":stid}));myControl.renderFunctions.translateTemplate(myControl.data.cartItemsList.cart.stuff[i],"cartViewer_"+stid);if(stid[0]=='%'){$parent.find(':input').attr({'disabled':'disabled'})}}}},getStuffIndexBySTID:function(stid){var L=myControl.data.cartItemsList.cart.stuff.length;var r=false;for(var i=0;i<L;i+=1){if(myControl.data.cartItemsList.cart.stuff[i].stid==stid){r=i;break;}}
return r;},updateCartQty:function(stid,qty,tagObj){if(stid){myControl.util.dump('got stid: '+stid);tagObj=$.isEmptyObject(tagObj)?{}:tagObj;tagObj.callback=tagObj.callback?tagObj.callback:'updateCartLineItem';tagObj.extension=tagObj.extension?tagObj.extension:'store_cart';tagObj.parentID='cartViewer_'+myControl.util.makeSafeHTMLId(stid);myControl.ext.store_cart.calls.cartItemUpdate.init(stid,qty);this.updateCartSummary();if(qty>=1){myControl.calls.ping.init(tagObj,'immutable');}
else{$('#cartViewer_'+myControl.util.makeSafeHTMLId(stid)).empty().remove();}}
else{myControl.util.dump(' -> a stid is required to do an update cart.');}},getCSVOfAccessories:function(){var csvArray=new Array();var proda;var prodArray=new Array();var i,j,L,M;M=myControl.data.cartItemsList.cart['stuff'].length;for(j=0;j<M;j+=1){if(proda=myControl.data.cartItemsList.cart['stuff'][j]['full_product']['zoovy:accessory_products']){prodArray=proda.split(',');L=prodArray.length
for(var i=0;i<L;i+=1){csvArray.push(prodArray[i])}
prodArray=[];}}
csvArray=$.grep(csvArray,function(n){return(n);});return myControl.util.removeDuplicatesFromArray(csvArray);}}}
return r;}