#!/bin/sh

export VERSION=201408

rm -Rf /httpd/static/zmvc/$VERSION
git clone -b $VERSION git@github.com:CommerceRack/anycommerce.git /httpd/static/zmvc/$VERSION

cd /httpd/static/zmvc/$VERSION
ln -fs app-admin.html index.html
ln -fs app-admin.html admin.html
cd /httpd/static/zmvc

