#!/bin/sh

export VERSION=201401

rm -Rf /httpd/static/zmvc/$VERSION
git clone -b $VERSION git@github.com:zoovy/AnyCommerce-Development.git /httpd/static/zmvc/$VERSION

cd /httpd/static/zmvc/$VERSION
ln -s app-admin.html index.html
ln -s app-admin.html admin.html
cd /httpd/static/zmvc

